version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gocritic
    - revive
    - misspell
    - unparam
    - unconvert
    - nilerr
    - errorlint
  settings:
    govet:
      enable-all: true
    errcheck:
      check-type-assertions: true
    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"
    gocritic:
      enabled-tags:
        - diagnostic
        - style

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

run:
  timeout: 5m

output:
  formats:
    colored-line-number: {}

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
