version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - misspell
    - unparam
    - unconvert
    - nilerr
    - errorlint
    - goconst
    - godox
  settings:
    govet:
      enable-all: true
    errcheck:
      check-type-assertions: true
    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"
    gocritic:
      enabled-tags:
        - diagnostic
        - style
    godox:
      keywords:
        - TODO
        - FIXME
        - HACK
        - XXX
    goconst:
      min-len: 3
      min-occurrences: 3

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

run:
  timeout: 5m

output:
  formats:
    text:
      path: stdout

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
