version: '3'

vars:
  BINARY_NAME: invento-service
  MAIN_PKG: ./cmd/app

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build the application binary
    cmds:
      - go build -o {{.BINARY_NAME}} {{.MAIN_PKG}}
    sources:
      - ./**/*.go
      - go.mod
      - go.sum

  test:
    desc: Run all tests
    cmds:
      - go test ./... -race -count=1

  test:cover:
    desc: Run tests with coverage
    cmds:
      - go test ./... -race -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix ./...

  fmt:
    desc: Format code with gofumpt
    cmds:
      - gofumpt -w .

  swagger:
    desc: Regenerate swagger documentation
    cmds:
      - swag init -g cmd/app/main.go --output docs --parseDependency --parseInternal

  tidy:
    desc: Tidy Go modules
    cmds:
      - go mod tidy

  run:
    desc: Run the application
    cmds:
      - go run {{.MAIN_PKG}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -f coverage.out coverage.html

  check:
    desc: Run all checks (lint + test + build)
    cmds:
      - task: lint
      - task: test
      - task: build
