CREATE TABLE IF NOT EXISTS tus_modul_uploads (
    id VARCHAR(36) PRIMARY KEY,
    user_id INTEGER NOT NULL,
    modul_id INTEGER NULL,
    upload_type VARCHAR(20) NOT NULL DEFAULT 'modul_create',
    upload_url VARCHAR(500) NULL,
    upload_metadata JSON NULL,
    file_size BIGINT NOT NULL,
    current_offset BIGINT DEFAULT 0,
    file_path VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL,
    progress DECIMAL(5,2) DEFAULT 0.00,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW() ,
    expires_at TIMESTAMP NOT NULL,
    CREATE INDEX idx_tus_modul_uploads_user_id ON roles(user_id),
    CREATE INDEX idx_tus_modul_uploads_modul_id ON roles(modul_id),
    CREATE INDEX idx_tus_modul_uploads_status ON roles(status),
    CREATE INDEX idx_tus_modul_uploads_expires_at ON roles(expires_at),
    CREATE INDEX idx_tus_modul_uploads_upload_type ON roles(upload_type),
    CREATE INDEX idx_tus_modul_uploads_status_expires ON roles(statusexpires_at),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (modul_id) REFERENCES moduls(id) ON DELETE CASCADE
) 
