CREATE TABLE IF NOT EXISTS tus_modul_uploads (
    id VARCHAR(36) PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    modul_id INT UNSIGNED NULL,
    upload_type VARCHAR(20) NOT NULL DEFAULT 'modul_create',
    upload_url VARCHAR(500) NULL,
    upload_metadata JSON NULL,
    file_size BIGINT NOT NULL,
    current_offset BIGINT DEFAULT 0,
    file_path VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL,
    progress DECIMAL(5,2) DEFAULT 0.00,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    INDEX idx_tus_modul_uploads_user_id (user_id),
    INDEX idx_tus_modul_uploads_modul_id (modul_id),
    INDEX idx_tus_modul_uploads_status (status),
    INDEX idx_tus_modul_uploads_expires_at (expires_at),
    INDEX idx_tus_modul_uploads_upload_type (upload_type),
    INDEX idx_tus_modul_uploads_status_expires (status, expires_at),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (modul_id) REFERENCES moduls(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
