CREATE TABLE IF NOT EXISTS otps (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    user_name VARCHAR(255) DEFAULT '',
    password_hash VARCHAR(512) DEFAULT '',
    code VARCHAR(255) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    attempts INT DEFAULT 0,
    max_attempts INT DEFAULT 5,
    is_used BOOLEAN DEFAULT false,
    resend_count INT DEFAULT 0,
    last_resend_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW() ,
    CREATE INDEX idx_otps_email ON roles(email),
    CREATE INDEX idx_otps_type ON roles(type),
    CREATE INDEX idx_otps_expires_at ON roles(expires_at),
    CREATE INDEX idx_otps_validation ON roles(emailtypeis_usedexpires_at)
) 
