INSERT INTO permissions (resource, action, label) VALUES
('Role', 'create', 'Buat role'),
('Role', 'read', 'Lihat role'),
('Role', 'update', 'Perbarui role'),
('Role', 'delete', 'Hapus role'),
('Permission', 'create', 'Buat permission'),
('Permission', 'read', 'Lihat permission'),
('Permission', 'update', 'Perbarui permission'),
('Permission', 'delete', 'Hapus permission'),
('User', 'create', 'Buat user'),
('User', 'read', 'Lihat user'),
('User', 'update', 'Perbarui user'),
('User', 'delete', 'Hapus user'),
('User', 'download', 'Download data user'),
('Modul', 'create', 'Buat modul'),
('Modul', 'read', 'Lihat modul'),
('Modul', 'update', 'Perbarui modul'),
('Modul', 'delete', 'Hapus modul'),
('Project', 'create', 'Buat project'),
('Project', 'read', 'Lihat project'),
('Project', 'update', 'Perbarui project'),
('Project', 'delete', 'Hapus project')
ON DUPLICATE KEY UPDATE resource=VALUES(resource);
